import Head from 'next/head';
import React, {useState} from 'react';

const settings = () => {
    const [count, setCount] = useState(0)

    return (
        <>
        <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Pagina settings</p>
      <button onClick={() => setCount(count + 1)}>{count}</button>
      </>
    );
};

export default settings;